In [1]:
#Library
# ---
# Librerias de selenium 

from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.support.ui import Select  # selccionar opciones de las lista desplegable
from selenium.webdriver.common.by import By  # permite seleccionar los elementos en un html
from selenium.webdriver.common.keys import Keys  # ingresar datos a un formulario
from selenium.common.exceptions import NoSuchElementException
# Opciones driver
from selenium.webdriver.chrome.options import Options
from seleniumbase import Driver

# dataframes
import pandas as pd
from pandas import json_normalize
import numpy as np

# Similamos comportamiento humano al añadir tiempos aleatorios
import time
from time import sleep
import random
from tqdm import tqdm

import requests 

# Manipular Json files
import json

from utils import *

In [2]:
# Open la página

options_chrome = Options()
options_chrome.add_argument('--disable-blink-features=AutomationControlled')

driver = Driver(browser="chrome", headless=False)



# Access to INDECOPI website - Denuncias de ciudadanos
url = 'https://servicio.indecopi.gob.pe/buscadorResoluciones/proteccion-consumidor.seam'
driver.get(url)
driver.maximize_window()

In [3]:
web_filter_consult = driver.find_element(By.XPATH, "//input[@id='FormListado1:txtTextoBusqueda']")

web_filter_consult.send_keys('Fraude financiero en bancos')

In [4]:
driver.find_element(By.XPATH, "//input[@id='FormListado1:b_RealizaBusqueda']").click()

In [ ]:
# links_pdf = driver.find_elements(By.XPATH, "//span[contains(@onclick,'descargar')]")

In [ ]:
num_pages = 7

data_full = {}

In [15]:
for i in tqdm(range(num_pages)):
    
    nro_resoluciones = []
    fecha_resoluciones = []
    exp_resoluciones = []
    denuncias = []
    summillas = []

    lsit_1 = driver.find_elements(By.XPATH, "//td[contains(@id, 'id134')]")
    nro_resoluciones.extend([x.text for x in lsit_1])
    
    lsit_2 = driver.find_elements(By.XPATH, "//td[contains(@id, 'id138')]")
    fecha_resoluciones.extend([x.text for x in lsit_2])

    lsit_3 = driver.find_elements(By.XPATH, "//td[contains(@id, 'id140')]")
    exp_resoluciones.extend([x.text for x in lsit_3])

    lsit_4 = driver.find_elements(By.XPATH, "//td[contains(@id, 'id142')]")
    denuncias.extend([x.text for x in lsit_4])

    lsit_5 = driver.find_elements(By.XPATH, "//td[contains(@id, 'sumilla')]")
    summillas.extend([x.text for x in lsit_5])
    
    links_pdf = driver.find_elements(By.XPATH, "//span[contains(@onclick,'descargar')]")
    
    dataframe_table = pd.DataFrame({'nro_resoluciones': nro_resoluciones,
                                     'fecha_resoluciones': fecha_resoluciones,
                                     'exp_resoluciones': exp_resoluciones,
                                     'denuncias': denuncias,
                                     'summillas': summillas})
    
    for link in links_pdf:
        time.sleep(random.randint(2, 3))
        link.click()    
     
    data_full[f'page_date_{i}'] = dataframe_table 
        
    driver.find_element(By.XPATH, "//*[@id='FormListado3:testpList:j_id114:9:cmlPage']").click()

    time.sleep(random.randint(5, 6))

100%|██████████| 7/7 [00:42<00:00,  6.07s/it]

In [ ]:
# //*[@id="FormListado3:testpList:j_id114:9:cmlPage"]

In [16]:
ResIndecopi = pd.concat( data_full.values() ).reset_index( drop = True )
ResIndecopi

,nro_resoluciones,fecha_resoluciones,exp_resoluciones,denuncias,summillas
0,3-2026/PS2,2026-01-05,003857-2025/PS2,"GUEVARA VASQUEZ, LUCY DORIS/RENTA CAR LIAM E.I...",>>ABANDONO >>ARCHIVO DEL PROCEDIMIENTO
1,4-2026/CPC-INDECOPI-PUN,2026-01-22,000022-2025/CPC-INDECOPI-PUN,DENUNCIANTE: JAVIER AMBROSIO PADILLA DIAZ / DE...,Declarar infundada en parte la denuncia interp...
2,8-2026/CPC-INDECOPI-CHT,2026-02-02,000068-2025/CPC-INDECOPI-CHT,DENUNCIANTE : ZENAIDA PAOLA MAGUIÑA FALCON DEN...,SEGUNDO: Denegar la solicitud de suspensión de...
3,9-2026/CPC-INDECOPI-CHT,2026-02-02,000074-2025/CPC-INDECOPI-CHT,DENUNCIANTE : GEREMIAS MATOS EGUSQUIZA DENUNCI...,PRIMERO: Declarar la confidencialidad de los A...
4,12-2026/CPC-INDECOPI-PUN,2026-02-26,000054-2025/CPC-INDECOPI-PUN,DENUNCIANTE: ELOÍSA ARCILA LUQUE CAYO / DENUNC...,Declarar fundado el procedimiento iniciado por...
...,...,...,...,...,...
166,2156-2026/PS2,2026-07-24,2480-2026/PS2,"DENUNCIANTES: ZEGARRA OTINIANO, CARLOS OSWALDO...",REGISTRO: 2480-2026/PS2 DENUNCIA - RESOLUCION ...
167,2231-2026/PS2,2026-08-05,2736-2026/PS2,"DENUNCIANTES: RAMIREZ GALVEZ, MARCO ANTONIO - ...",REGISTRO: 2736-2026/PS2 DENUNCIA - RESOLUCION ...
168,2243-2026/PS2,2026-08-07,2925-2026/PS2,"DENUNCIANTES: MASCO URRUTIA, JAIME - DENUNCIAD...",REGISTRO: 2925-2026/PS2 DENUNCIA - RESOLUCION ...
169,2265-2026/PS2,2026-08-11,2932-2026/PS2,"DENUNCIANTES: YUJCRE RIOS, JAIME ANTONIO - DEN...",REGISTRO: 2932-2026/PS2 DENUNCIA - RESOLUCION ...
170,2293-2026/CC1,2026-07-22,325-2026/CC1,"DENUNCIANTES: AVILA HINOSTROZA, BETSY PAMELA -...",REGISTRO: 325-2026/CC1 APELACION - RESOLUCION ...

In [ ]:
ResIndecopi.to_csv(r"..\..\data\raw\ResIndecopi.csv", 
                   index=False)

### Load and cleaning dataset

In [7]:
ResIndecopi = pd.read_csv(r"..\..\data\raw\ResIndecopi.csv",
                           encoding='utf-8')

In [8]:
ResIndecopi

,nro_resoluciones,fecha_resoluciones,exp_resoluciones,denuncias,summillas
0,3-2026/PS2,2026-01-05,003857-2025/PS2,"GUEVARA VASQUEZ, LUCY DORIS/RENTA CAR LIAM E.I...",>>ABANDONO >>ARCHIVO DEL PROCEDIMIENTO
1,4-2026/CPC-INDECOPI-PUN,2026-01-22,000022-2025/CPC-INDECOPI-PUN,DENUNCIANTE: JAVIER AMBROSIO PADILLA DIAZ / DE...,Declarar infundada en parte la denuncia interp...
2,8-2026/CPC-INDECOPI-CHT,2026-02-02,000068-2025/CPC-INDECOPI-CHT,DENUNCIANTE : ZENAIDA PAOLA MAGUIÑA FALCON DEN...,SEGUNDO: Denegar la solicitud de suspensión de...
3,9-2026/CPC-INDECOPI-CHT,2026-02-02,000074-2025/CPC-INDECOPI-CHT,DENUNCIANTE : GEREMIAS MATOS EGUSQUIZA DENUNCI...,PRIMERO: Declarar la confidencialidad de los A...
4,12-2026/CPC-INDECOPI-PUN,2026-02-26,000054-2025/CPC-INDECOPI-PUN,DENUNCIANTE: ELOÍSA ARCILA LUQUE CAYO / DENUNC...,Declarar fundado el procedimiento iniciado por...
...,...,...,...,...,...
166,2156-2026/PS2,2026-07-24,2480-2026/PS2,"DENUNCIANTES: ZEGARRA OTINIANO, CARLOS OSWALDO...",REGISTRO: 2480-2026/PS2 DENUNCIA - RESOLUCION ...
167,2231-2026/PS2,2026-08-05,2736-2026/PS2,"DENUNCIANTES: RAMIREZ GALVEZ, MARCO ANTONIO - ...",REGISTRO: 2736-2026/PS2 DENUNCIA - RESOLUCION ...
168,2243-2026/PS2,2026-08-07,2925-2026/PS2,"DENUNCIANTES: MASCO URRUTIA, JAIME - DENUNCIAD...",REGISTRO: 2925-2026/PS2 DENUNCIA - RESOLUCION ...
169,2265-2026/PS2,2026-08-11,2932-2026/PS2,"DENUNCIANTES: YUJCRE RIOS, JAIME ANTONIO - DEN...",REGISTRO: 2932-2026/PS2 DENUNCIA - RESOLUCION ...
170,2293-2026/CC1,2026-07-22,325-2026/CC1,"DENUNCIANTES: AVILA HINOSTROZA, BETSY PAMELA -...",REGISTRO: 325-2026/CC1 APELACION - RESOLUCION ...

In [9]:
ResIndecopi['EntidadFinanciera'] = ResIndecopi['denuncias'].apply(lambda x: quitar_tildes(re.split(r'[;:/]', x)[-1].strip()).lower())

In [11]:
ResIndecopi['EntidadFinanciera'].value_counts()

EntidadFinanciera
banco de credito del peru                                                                          33
banco interamericano de finanzas                                                                   18
banco de credito del peru s.a.                                                                     16
infinance xp s.a.                                                                                  12
banco bbva peru                                                                                    10
banco ripley peru s.a.                                                                              9
banco internacional del peru-interbank                                                              8
scotiabank peru saa                                                                                 8
caja municipal de ahorro y credito cusco s.a. – cmac cusco s.a.                                     4
banco de la nacion                                                                                  4
financiera oh! s.a. o financiera oh s.a.                                                            4
banco pichincha                                                                                     4
banco de credito del peru s.a.1 (banco)                                                             3
caja municipal de ahorro y credito cusco s.a.                                                       3
banco bbva peru s.a.                                                                                3
scotiabank peru s.a.a.                                                                              2
cmac - huancayo s.a.                                                                                2
pacifico compania de seguros y reaseguros s.a.                                                      2
caja rural de ahorro y credito cencosud scotia peru s.a.                                            2
caja municipal de ahorro y credito de arequipa s.a. - caja arequipa                                 2
scotiabank peru sociedad anonima abierta                                                            1
banco bbva peru s.a                                                                                 1
banco internacional del peru sociedad anonima abierta – interbank                                   1
financiera oh! s.a. o financiera oh s.a                                                             1
financiera oh s.a.                                                                                  1
banco internacional del peru s.a.a,                                                                 1
banco de credito del peru (bcp) banco bbva peru (bbva) mi banco – banco de la microempresa s.a.     1
banco gnb peru s.a.                                                                                 1
banco bbva peru s.a. (el banco)                                                                     1
scotiabank peru s.a.a. (banco)                                                                      1
scotiabank peru s.a.a. (el banco)                                                                   1
caja municipal de ahorro                                                                            1
pacifico compania de seguros y reaseguros                                                           1
hipermercados tottus s.a                                                                            1
banco de credito del peru s.a                                                                       1
banco de comercio                                                                                   1
banco internacional del peru s.a.a.-interbank                                                       1
scotiabank peru s.a.a. (scotiabank)                                                                 1
live entertainment sac                                                                              1
america movil peru s.a.c.                                                                           1
eede tarjetas peruanas prepago s.a.                                                                 1
tai loy s.a.                                                                                        1
Name: count, dtype: int64

In [21]:
ResIndecopi['summillas'].to_list()

['>>ABANDONO >>ARCHIVO DEL PROCEDIMIENTO',
 'Declarar infundada en parte la denuncia interpuesta por el señor Javier Ambrosio Padilla Diaz, en contra de Scotiabank Perú Sociedad Anónima Abierta, por infracción al artículo 19º del Código de Prote... Ver más contenido.',
 'SEGUNDO: Denegar la solicitud de suspensión de procedimiento formulada por el Banco de Crédito del Perú S.A., conforme lo analizado en la presente resolución. TERCERO: Denegar la solicitud de inclusió... Ver más contenido.',
 'PRIMERO: Declarar la confidencialidad de los Anexos 2 y 3, así como de aquellas secciones del escrito del 27 de octubre de 2025, por constituir datos personales cuya reserva ha sido reconocida por ley... Ver más contenido.',
 'Declarar fundado el procedimiento iniciado por la señora Eloísa Arcila Luque Cayo en contra del Banco Internacional del Perú Sociedad Anónima Abierta - Interbank, por infracción al artículo 19° del Có... Ver más contenido.',
 'REGISTRO: 54-2025/CPC-PUN DENUNCIA - RESOLUCION FINAL',
 'Revocar la Resolución Final N° 0589-2025/PS0-INDECOPI-LAM del 18 de Julio del 2025 emitida por el Órgano Resolutivo de Procedimientos Sumarísimos de la Oficina Regional del Indecopi de Lambayeque que ... Ver más contenido.',
 'SUMILLA: En el procedimiento iniciado por la señora Carolina Rivera Diaz en contra de Banco De Crédito Del Perú por presuntas infracciones a la Ley N°29571 - Código de Protección y Defensa del Consumi... Ver más contenido.',
 'Iniciar procedimiento administrativo sancionador en contra de Financiera Oh S.A. en mérito a la denuncia presentada por la señora Achahui Mollo por: i) Presunta infracción al artículo 19° del Código d... Ver más contenido.',
 'REGISTRO: 366-2025/CPC-JUN DENUNCIA - RESOLUCION FINAL',
 'PRIMERO: Denegar la solicitud de improcedencia formulada por el Banco de Crédito del Perú S.A., conforme lo analizado en la presente resolución. SEGUNDO: Declarar fundada la denuncia interpuesta por G... Ver más contenido.',
 'REGISTRO: 87-2025/CPC-CHI DENUNCIA - RESOLUCION FINAL',
 'MATERIA : PROCEDIMIENTO ADMINISTRATIVO SANCIONADOR DEBER DE IDONEIDAD MEDIDAS CORRECTIVAS GRADUACIÓN DE LA SANCIÓN COSTAS Y COSTOS ACTIVIDAD : SISTEMA FINANCIERO BANCARIO',
 'En el procedimiento administrativo iniciado por el señor Fidel Frank Calle Solórzano contra Banco de Crédito del Perú, la Comisión de la Oficina Regional del Indecopi de Lambayeque, ha resuelto declar... Ver más contenido.',
 'SUMILLA: Declarar FUNDADA la denuncia presentada por el señor Nazario Morales Medina contra Caja Municipal de Ahorro y Crédito Cusco S.A. por infracción del artículo 19° de la Ley 29571, Código de Pr... Ver más contenido.',
 'SUMILLA: Declarar FUNDADA la denuncia interpuesta por Amazon Wildlife Perú E.I.R.L. contra el Banco de Crédito del Perú por infracción del artículo 19° de la Ley Nº 29571 – Código de Protección y Defe... Ver más contenido.',
 'Declarar fundada la denuncia interpuesta por el señor Julio Edilberto Milla Mejía contra Banco Internacional del Perú S.A.A. – Interbank, por infracción al artículo 19° del Código de Protección y Defe... Ver más contenido.',
 '>>ARCHIVO DEL PROCEDIMIENTO',
 'MATERIA : PROCEDIMIENTO ADMINISTRATIVO SANCIONADOR DEBER DE IDONEIDAD MEDIDAS CORRECTIVAS GRADUACIÓN DE LA SANCIÓN COSTAS Y COSTOS ACTIVIDAD : OTROS TIPOS DE INTERMEDIACION MONETARIA',
 'Concluir de manera anticipada la denuncia presentada contra Banco BBVA Perú S.A. en mérito al desistimiento de la denuncia y pretensión, comunicado mediante escrito del 29 de diciembre de 2025, por pa... Ver más contenido.',
 'REGISTRO: 1937-2025/ILN-PS0 DENUNCIA - RESOLUCION FINAL',
 'Ordenar a Banco de la Nación como medida correctiva de oficio que en un plazo de quince (15) días hábiles, contado a partir del día siguiente de notificada la presente resolución, cumpla con regulariz... Ver más contenido.',
 'Ordenar al Scotiabank Perú S.A.A. como medida correctiva reparadora que, en el plazo de quince (15) días hábiles contados a partir del día siguiente de notificada la presente resolución cumpla con: (i... Ver más contenido.',
 'Sancionar a Banco BBVA Perú S.A. con una multa al acreditarse la infracción a lo establecido en el artículo 19° del Código de Protección y Defensa del Consumidor, por las consideraciones expuestas en ... Ver más contenido.',
 'REGISTRO: 102-2026/PS0-TAC DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 868-2025/PS0-JUN DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 51-2026/CPC-CHI DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 411-2025/CPC-JUN DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 887-2025/PS0-JUN DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 139-2026/PS0-CHT DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 895-2025/PS0-JUN DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 894-2025/PS0-JUN DENUNCIA - RESOLUCION FINAL',
 '>>ARCHIVO DEL PROCEDIMIENTO >>IMPROCEDENTE-FALTA DE INTERÉS PARA OBRAR',
 '>>INFRACCION A LAS NORMAS DE PROTECCION AL CONSUMIDOR-INFRACCIÓN',
 'REGISTRO: 63-2026/CPC-CHI APELACION - RESOLUCION FINAL',
 'MATERIAS : IMPROCEDENCIA POR FALTA DE INTERÉS PARA OBRAR DEBER DE IDONEIDAD DEBER DE INFORMACIÓN MEDIDAS CORRECTIVAS GRADUACIÓN DE SANCIÓN',
 'MATERIA : PROCEDIMIENTO ADMINISTRATIVO SANCIONADOR DEBER DE IDONEIDAD RECLAMO DE PRODUCTOS FINANCIEROS MEDIDAS CORRECTIVAS GRADUACIÓN DE LA SANCIÓN COSTAS Y COSTOS ACTIVIDAD : OTROS TIPOS DE INTERMEDI... Ver más contenido.',
 'Declarar improcedente la denuncia interpuesta por la señora Ysique contra Banco BBVA, por presunta infracción al artículo 19 del Código',
 'MATERIAS : PROTECCIÓN AL CONSUMIDOR DEBER DE IDONEIDAD MEDIDAS CORRECTIVAS GRADUACIÓN DE LA SANCIÓN COSTAS Y COSTOS',
 'REGISTRO: 448-2025/PS0-LOR DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 321-2025/PS0-LOR DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 128-2024/PS0-LOR DENUNCIA - RESOLUCION FINAL',
 '>>INFRACCION A LAS NORMAS DE PROTECCION AL CONSUMIDOR-INFRACCIÓN >>ARCHIVO DEL PROCEDIMIENTO',
 '>>ARCHIVO DEL PROCEDIMIENTO',
 'Archivar el presente procedimiento administrativo sancionador iniciado contra Scotiabank Perú S.A.A., por presunta infracción al artículo 19° del Código de Protección y Defensa del Consumidor, por las... Ver más contenido.',
 'Archivar el procedimiento administrativo sancionador instaurado en contra de Banco de Crédito del Perú, por presunta infracción a lo establecido en el artículo 19° del Código de Protección y Defensa d... Ver más contenido.',
 'REGISTRO: 142-2026/PS0-TAC DENUNCIA - RESOLUCION FINAL',
 'MATERIA : PROCEDIMIENTO ADMINISTRATIVO SANCIONADOR DEBER DE IDONEIDAD MEDIDAS CORRECTIVAS GRADUACIÓN DE LA SANCIÓN COSTAS Y COSTOS ACTIVIDAD : SISTEMA FINANCIERO BANCARIO',
 'MATERIA : PROCEDIMIENTO ADMINISTRATIVO SANCIONADOR DEBER DE IDONEIDAD RECLAMO DE PRODUCTOS O SERVICIOS FINANCIEROS MÉTODOS ABUSIVOS DE COBRANZA MEDIDAS CORRECTIVAS GRADUACIÓN DE LA SANCIÓN COSTAS Y CO... Ver más contenido.',
 '>>IMPROCEDENTE-FALTA DE COMPETENCIA DEL INDECOPI >>INFRACCION A LAS NORMAS DE PROTECCION AL CONSUMIDOR-ALLANAMIENTO >>ARCHIVO DEL PROCEDIMIENTO',
 'MATERIAS : PROTECCIÓN AL CONSUMIDOR DEBER DE IDONEIDAD DEBER DE ATENCIÓN DE RECLAMOS MEDIDAS CORRECTIVAS GRADUACIÓN DE SANCIÓN',
 'Archivar el procedimiento administrativo sancionador instaurado en contra de Banco de la Nación por presunta infracción a lo establecido en el artículo 19° del Código de Protección y Defensa del Consu... Ver más contenido.',
 'eclarar FUNDADA la denuncia interpuesta por la señora Yanet Yuditza Bustamante Rozas contra el Banco de Crédito del Perú por infracción al artículo 19° de la Ley Nº 29571 – Código de Protección y Defe... Ver más contenido.',
 'Declarar infundada la denuncia interpuesta contra Scotiabank Perú S.A.A., por presunta infracción al artículo 19 del Código de Protección y Defensa del Consumidor',
 'REGISTRO: 11-2026/CPC-LAL APELACION - RESOLUCION FINAL',
 'MATERIA : PROCEDIMIENTO ADMINISTRATIVO SANCIONADOR DEBER DE IDONEIDAD MEDIDAS CORRECTIVAS GRADUACIÓN DE LA SANCIÓN COSTAS Y COSTOS ACTIVIDAD : OTROS TIPOS DE INTERMEDIACION MONETARIA',
 'MATERIAS : PROTECCIÓN AL CONSUMIDOR DEBER DE IDONEIDAD ATENCIÓN DE RECLAMOS ALLANAMIENTO MEDIDAS CORRECTIVAS GRADUACIÓN DE LA SANCIÓN COSTOS Y COSTAS',
 'MATERIA : PROCEDIMIENTO ADMINISTRATIVO SANCIONADOR DEBER DE IDONEIDAD MEDIDAS CORRECTIVAS GRADUACIÓN DE LA SANCIÓN COSTAS Y COSTOS ACTIVIDAD : OTROS TIPOS DE INTERMEDIACION MONETARIA',
 'REGISTRO: 461-2025/CPC-LAL DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 4519-2025/PS2 DENUNCIA - RESOLUCION FINAL',
 'Declarar infundada la denuncia interpuesta por el señor Kerwin Jesús Leandro Huamaní Quilcahuanca contra Banco de Crédito del Perú S.A., por presunta infracción al artículo 88.1 del Código de Protecci... Ver más contenido.',
 'Declarar IMPROCEDENTE el procedimiento administrativo sancionador iniciado contra el Banco de Crédito del Perú ante la denuncia interpuesta el señor Ronald Del Pozo Cruz por presunta infracción a lo e... Ver más contenido.',
 'MATERIA : PROCEDIMIENTO ADMINISTRATIVO SANCIONADOR DEBER DE IDONEIDAD MEDIDAS CORRECTIVAS GRADUACIÓN DE LA SANCIÓN COSTAS Y COSTOS ACTIVIDAD : OTRO TIPO DE INTERMEDIACIÓN FINANCIERA',
 'Declarar infundada la denuncia interpuesta por el señor Pedro Terrones Terán contra Banco BBVA Perú S.A., por presunta infracción al artículo 56.1, inciso b), del Código de Protección y Defensa del Co... Ver más contenido.',
 'Declarar infundada la denuncia interpuesta por el señor Dedicación Daniel Gamarra Mata contra Banco de Crédito del Perú S.A., por presunta infracción al artículo 56.1, inciso b), del Código de Protecc... Ver más contenido.',
 'REGISTRO: 123-2025/ILN-CPC DENUNCIA - RESOLUCION FINAL',
 'MATERIA : PROCEDIMIENTO ADMINISTRATIVO SANCIONADOR DEBER DE IDONEIDAD MEDIDAS CORRECTIVAS GRADUACIÓN DE LA SANCIÓN COSTAS Y COSTOS ACTIVIDAD : SISTEMA FINANCIERO BANCARIO',
 'REGISTRO: 61-2018/CC1 DENUNCIA - RESOLUCION FINAL',
 'Declarar la nulidad parcial de la Resolución 1 del 7 de noviembre de 2025, en los extremos referidos en que imputó a Banco de Crédito del Perú S.A. y Pacífico Compañía de Seguros y Reaseguros S.A.',
 'REGISTRO: 1495-2025/CC1 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 4440-2025/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 119-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 176-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 4458-2025/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 912-2025/CC1 APELACION - RESOLUCION FINAL',
 'REGISTRO: 1693-2025/CC1 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 1807-2025/CC1 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 1915-2025/CC1 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 53-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 4573-2025/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 363-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'MATERIA : PROCEDIMIENTO ADMINISTRATIVO SANCIONADOR DEBER DE IDONEIDAD MEDIDAS CORRECTIVAS GRADUACIÓN DE LA SANCIÓN COSTAS Y COSTOS ACTIVIDAD : OTRO TIPO DE INTERMEDIACIÓN FINANCIERA',
 'REGISTRO: 1865-2025/CC1 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 1822-2025/CC1 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 389-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 4032-2025/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 222-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 1841-2025/CC1 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 1899-2025/CC1 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 1932-2025/CC1 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 135-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 378-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 1957-2025/CC1 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 2020-2025/CC1 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 497-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 1940-2025/CC1 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 255-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 415-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 620-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 672-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 651-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 688-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 773-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 626-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 567-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 788-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 509-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 532-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 784-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 862-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 738-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 2647-2025/CC1 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 106-2026/CC1 APELACION - RESOLUCION FINAL',
 'REGISTRO: 842-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 2132-2025/CC1 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 1006-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 1187-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 1129-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 1134-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 905-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 1220-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'MATERIAS : PROTECCIÓN AL CONSUMIDOR DEBER DE IDONEIDAD',
 'REGISTRO: 1165-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 2871-2025/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 1381-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 2530-2025/CC1 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 1270-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 990-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 1275-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 915-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 1405-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 1505-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 1418-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 1522-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 1271-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 1277-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 1545-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 1546-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 1593-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 1659-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 2568-2025/CC1 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 1386-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 1133-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 2584-2025/CC1 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 1738-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 1740-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 2678-2025/CC1 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 1899-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 949-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 1943-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 1765-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 1866-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 3034-2025/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 3531-2025/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 2735-2025/CC1 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 1830-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 1651-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 1600-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 1783-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 1540-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 2071-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 2484-2025/CC1 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 1768-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 2070-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 1947-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 2156-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 2480-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 2736-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 2925-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 2932-2026/PS2 DENUNCIA - RESOLUCION FINAL',
 'REGISTRO: 325-2026/CC1 APELACION - RESOLUCION FINAL']

In [18]:
ResIndecopi.columns

Index(['nro_resoluciones', 'fecha_resoluciones', 'exp_resoluciones',
       'denuncias', 'summillas', 'EntidadFinanciera'],
      dtype='str')

In [22]:
ResIndecopi.to_csv(r"..\..\data\raw\ResIndecopi_metadata_pdf.csv", 
                   index=False)